CREATE DATABASE TROCAS_DEVOLUCOES
USE TROCAS_DEVOLUCOES

CREATE TABLE TROCAS_DEVOLUCOES(
CD_TROCA INT IDENTITY(1,1) NOT NULL,
DS_DIA INT CHECK (DS_DIA < 31 AND DS_DIA > 1) NOT NULL,
DS_MES INT CHECK (DS_MES < 12 AND DS_MES > 1) NOT NULL,
DS_ANO INT NOT NULL,
NM_CLIENTE VARCHAR(50) NOT NULL,
DS_MOTIVO VARCHAR(100) NOT NULL,
NM_VENDEDORA VARCHAR(10) NOT NULL,
DS_STATUS VARCHAR(9) CHECK(DS_STATUS = 'Resolvido' or DS_STATUS = 'Pendente') NULL,
DS_FRETE VARCHAR(2) CHECK(DS_FRETE = 'ER' OR DS_FRETE = 'PC') NOT NULL,
CONSTRAINT PK_TROCA PRIMARY KEY (CD_TROCA))

DROP TABLE TROCAS_DEVOLUCOES
SELECT * FROM TROCAS_DEVOLUCOES

DELETE FROM TROCAS_DEVOLUCOES WHERE CD_TROCA = 2